name: DevSecOps-Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # This adds a manual "Play" button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t juice-shop .
