name: "🛡️ JuiceShop Security Shield"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: 🛡️ Gitleaks (Full Scan)
        run: |
          # We download the gitleaks tool and run it directly on the whole folder
          docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --source="/path" --verbose --redact
        continue-on-error: true
      - name: 🛡️ Trivy (Manual Scan - No Permissions Error)
        run: |
          # 1. Download the tool into the current folder
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v0.48.3
          
          # 2. Run it directly from the current folder (./trivy)
          # We'll use 'vuln' to find the "Tainted Ingredients"
          ./trivy fs --scanners vuln --severity CRITICAL,HIGH .
        continue-on-error: true
     
      - name: Build Docker Image
        run: |
          docker build -t juice-shop .
          echo "✅ Docker build successful!"
