name: "🛡️ JuiceShop Security Shield"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: 🛡️ Gitleaks (Full Scan)
        run: |
          # We download the gitleaks tool and run it directly on the whole folder
          docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --source="/path" --verbose --redact
        continue-on-error: true
      - name: 🛡️ Trivy (The "Show Me The Files" Scan)
        run: |
          # 1. We run the container and ask it to list what it sees in /path
          echo "--- INTERNAL DOCKER CHECK ---"
          docker run --rm -v ${{ github.workspace }}:/path alpine ls -R /path
          
          echo "--- STARTING ACTUAL SCAN ---"
          # 2. If the files show up above, this scan WILL work
          docker run --rm -v ${{ github.workspace }}:/path \
            aquasec/trivy:latest fs \
            --scanners vuln \
            --severity CRITICAL,HIGH \
            /path
        continue-on-error: true
     
      - name: Build Docker Image
        run: |
          docker build -t juice-shop .
          echo "✅ Docker build successful!"
