name: "🛡️ JuiceShop Security Shield"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: 🛡️ Gitleaks (Full Scan)
        run: |
          # We download the gitleaks tool and run it directly on the whole folder
          docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --source="/path" --verbose --redact
        continue-on-error: true
      - name: 📦 Generate Lockfile (Without full install)
        run: |
          # This creates the 'package-lock.json' without downloading 500MB of stuff
          npm install --package-lock-only 

      - name: 🛡️ Trivy Scan (Now with Lockfile)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app \
            aquasec/trivy:latest fs --scanners vuln /app
     
      - name: Build Docker Image
        run: |
          docker build -t juice-shop .
          echo "✅ Docker build successful!"
